os: windows
sudo: false
language: cpp

addons:
  sonarcloud:
    organization: "geoffray-adde-sonarsource-github"
    token:
      secure: "fGpoRLKINvIAfQjoQRFtzjMh8tMXfabbHvdGmL9WSlGupzFrLg1cr7uYAAXVYe2PKZ8X6XM8e0TCRnYc1tFMtfDZ1kQeCkWqjlw1VjPJymgEcywUXOlzV4zFU9Lr73gFbLPuow3riEYC2zQg26bPbVVZI7tDzQHI6K5hV4YyXr1ZO8p3bDancDOMD0N05XJgMUkTBjfiIv0v8PUYw9LihFSZDnuc22oOpAZbIGk5zM1IaP9Bs0nllsmA9JGVzOb/xjDv36jkYiMSB4he1zhrXQ0MLKnqsch9H2NVUszhHs/1Fs5go7AbK+o4Za4SHGDFwY+j/LWEMkCPCpy0Vhv7N3zMjdblFqDnR/qDitRhTLl/Jm1nWvjyVKh/hZmuSWYZoCT3rRR/ydJ1//tIvFl/0kalif8tYDrqiWS2pXCfUSVW6ExvrmkmcG7zJknAJognojyXCPx0jqwaMkVV+/tYhCgvnRE3y7GKImQccCNkBw27oc7kMybLaeAXFztQkFaw1xEfbFVsVj6zuD1dXllVLY1n70nmIuNmTUUgdhNcMChi8f8ENhI8FTRKC0Ee+WbgbXER/7V+v76LV659ypYWFrbD0xisVBHdkzUkkC+jNoH7acMpzI05G9DIVXWhbyZ7+lnMc8CaoOt7jkxbAVpFCJsR0hDFmFflO8aVWT0F1rc="


script:
# Install java
  - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - choco install jdk8 -params 'installdir=c:\\jdk' -y
# Download build-wrapper
  - rm -rf build-wrapper-win-x86.zip build-wrapper-linux-x86
  - curl "https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip" --output build-wrapper-win-x86.zip
  - unzip build-wrapper-win-x86.zip
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir bw-output cmake --build build/
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - ${TRAVIS_HOME}/.sonarscanner/sonar-scanner/bin/sonar-scanner.bat

cache:
  directories:
    - '$HOME/.sonar/cache'
